# Generated by Django 3.2.9 on 2021-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G1DB_Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.TextField(db_column='uid', primary_key=True, serialize=False),
        ),
    ]
