# Generated by Django 3.2.9 on 2021-11-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G1DB_Site', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.TextField(db_column='uid', max_length=255, primary_key=True, serialize=False),
        ),
    ]
