# Generated by Django 3.2.9 on 2021-11-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G1DB_Site', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(db_column='uid', max_length=255, primary_key=True, serialize=False),
        ),
    ]
