# Generated by Django 3.2.9 on 2021-12-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G1DB_Site', '0005_rankdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='itemid',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
